version: 1.0
app:
  instances: 1
  version: b81bcdb8-609e-4a4a-9006-b67acc208f83
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
  mounts:
    - path: /opt/ol/wlp/usr/servers/defaultServer/configDropins/overrides/myconfig.xml
      value: |
        <server>
            <var name="io_openliberty_sample_system_inMaintenance" value="false"/>
        </server>
