version: 1.0
app:
  instances: 1
  version: 4eace740-8dcc-482b-ab63-8e3fddd2f84f
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
  mounts:
    - path: /opt/ol/wlp/usr/servers/defaultServer/configDropins/overrides/myconfig.xml
      value: |
        <server>
            <var name="io_openliberty_sample_system_inMaintenance" value="false"/>
        </server>
