version: 1.0
app:
  instances: 1
  version: 6fa70826-6389-448e-a686-b1c2510b74fc
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
  mounts:
    - path: /opt/ol/wlp/usr/servers/defaultServer/configDropins/overrides/myconfig.xml
      value: |
        <server>
            <var name="io_openliberty_sample_system_inMaintenance" value="false"/>
        </server>
