version: 1.0
app:
  instances: 1
  version: 88b87158-8d05-43b9-88e6-63d759657412
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
  mounts:
    - path: /opt/ol/wlp/usr/servers/defaultServer/configDropins/overrides/myconfig.xml
      value: |
        <server>
            <var name="io_openliberty_sample_system_inMaintenance" value="false"/>
        </server>
